---
#- name: Configuration du serveur mariadb pour rundeck
#  hosts: mariadb
#  become: True
#  vars:
#    mariadb_conf_file: /etc/mysql/my.cnf
#    rundeck_db_name: rundeck
#    tuning_file_orig: templates/optimize.j2
#    tuning_file_dest: /etc/sysctl.d/optimize.conf
#    limit_file_orig: templates/optimize.j2
#    limit_file_dest: /etc/security/limits.d/db_limits.conf
#  roles:
#    - optimize_server
#    - { role: mariadb, rundeck_db_user: rundeck,  rundeck_db_password: rundeck }

- name: Configuration du serveur rundeck
  hosts: rundeck
  become: True
  vars:
    # Variables for Tomcat
    tomcat_major_version: 8
    tomcat_version: 8.0.36
    tomcat_folder: /usr/share/tomcat{{ tomcat_major_version }}
    tomcat_user: tomcat
    tomcat_group: tomcat
    tomcat_path: /usr/share/tomcat # Link to the actual tomcat installation folder

    # Variables for MariaDB
    mariadb_conf_file: /etc/mysql/my.cnf
    rundeck_db_name: rundeck
    my_sql_port: 3306

    env_file: /etc/environment
    rundeck_war: rundeck-2.6.9.war
    rundeck_repo: http://download.rundeck.org/war
    rundeck_conf_file: "{{ rundeck_base }}/etc/rundeck-config.properties"
    rundeck_framework_file: "{{ rundeck_base }}/etc/framework.properties"
    rundeck_profile_file: "{{ rundeck_base }}/etc/profile"
    rundeck_log_file: "{{ rundeck_base }}/etc/log4j.properties"
    rundeck_auth_file: "{{ rundeck_base }}/etc/jaas-loginmodule.conf"
    rundeck_useraccount_file: "{{ rundeck_base }}/etc/realm.properties"
  roles:
    - tomcat
 #   - mariadb
    - rundeck
  
