- name: Add repositories
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present

- name: Add repositories
  apt_repository: repo='deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' state=present

- name: Add apt key
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886 

- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - oracle-java8-installer
    - mariadb-client
    - vim
